# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Create vector tiles
on:
  workflow_call:
  push:
    branches:
      - main
  schedule:
    - cron: "1 2 * * 3"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-vector-tiles:
    runs-on: ubuntu-latest

    steps:
      - uses: nyurik/action-setup-postgis@v2
        id: postgres
    
      - run: psql -v ON_ERROR_STOP=1 -c 'SELECT PostGIS_Full_Version();' "$CONNECTION_STR"
        env:
          CONNECTION_STR: ${{ steps.postgres.outputs.connection-uri }}

      - uses: taiki-e/install-action@v2
        with: { tool: martin } # also includes martin-cp

      - run: sudo apt update && sudo apt install gdal-bin

      - uses: actions/checkout@v4
        with:
          repository: markusstraub/radlkarte
          path: radlkarte

      - run: |
          APPEND=""
          for GEOJSON in radlkarte/data/radlkarte-*.geojson; do
            if [[ $GEOJSON == *"radlkarte-example.geojson" ]] || [[ $GEOJSON == *"radlkarte-rendertest.geojson" ]]; then
              continue
            fi
            ogr2ogr -f PostgreSQL "${CONNECTION_STR}" -nln radlkarte ${APPEND} ${GEOJSON}
            APPEND="-append"
          done
        env:
          CONNECTION_STR: ${{ steps.postgres.outputs.connection-uri }}

      - run: mkdir -pv tileset

      - run: |
          martin-cp \
           --source radlkarte \
           --output-file=tileset/radlkarte.mbtiles \
           --min-zoom 9 \
           --max-zoom 16 \
           --bbox="8.8587, 45.7823, 17.1608, 49.5752" \
           --concurrency 2 \
           "${CONNECTION_STR}"
        env:
          CONNECTION_STR: ${{ steps.postgres.outputs.connection-uri }}

      - uses: actions/upload-artifact@v4
        with:
          name: tileset
          path: tileset/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: tileset/

  deploy-pages:
      runs-on: ubuntu-latest
      needs: create-vector-tiles
      environment: 
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      permissions:
        id-token: write
        pages: write
      steps:
        - uses: actions/deploy-pages@v4
          id: deployment
