# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Reactivate scheduled workflow
on:
  workflow_call:
  push:
    branches:
      - main
  schedule:
    - cron: "1 2 */59 * *"

permissions:
  contents: read

jobs:
  reactivate-scheduled-workflow:
    runs-on: ubuntu-latest

    steps:
      - run: echo "DEBUGDEBUGDEBUG"
      - run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN}}" \
          https://api.github.com/repos/${REPOSITORY}/actions/workflows/create-vector-tiles/enable
        env:
          REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
      #- run: curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows/create-vector-tiles/enable
      #- run: curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows/re-activate-workflow/enable
